services:
  postgres:
    image: postgres:18
    container_name: figurant-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_classroom
    ports:
      - "5432:5432"
    volumes:
      - ./.data/postgres:/var/lib/postgresql
