sonar.projectKey=Figurant
sonar.projectName=Figurant
sonar.sources=apps/web/src,apps/backend/src,apps/tauri/src, packages/ui/src,packages/shared/src,packages/frontend-utils/src
sonar.inclusions=**/*.ts,**/*.tsx,**/*.js,**/*.jsx
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/.pnpm/**,**/dist/**,**/.turbo/**,**/coverage/**, **/prisma/**, **/generated/**
sonar.scm.exclusions.disabled=true
